import os
import time
import project_parameters
from selenium import webdriver
from subtests import test_applygiftcards
from subtests import test_getgiftcards
from subtests import test_getorder
from subtests import test_product_mobile_web
from subtests import test_reportstepfinish
from subtests import test_sendordercornercloud
from subtests import test_shipping_mobile_web
import pytest


"""
This pytest test was automatically generated by TestProject
        Project: AutomationOrderBestBuy
        Package: TestProject.Generated.Tests.AutomationOrderBestBuy
        Test: GUEST_ORDER_WEB_MOBILE
        Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
        Generated on 07/29/2021, 20:22:27
"""

def drivercall():
        global driver   
        #project_parameters.zone = os.getenv('Zone', 'orderZoneOhio')
        #test_getorder.test_main()
        print("starting grid")
        capabilities = {"platformName": "Android","browserName": "chrome"}
        driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=capabilities)
        print("grid has been achieved")
        
        driver.implicitly_wait(20)
        time.sleep(3)
        device = driver.capabilities['deviceName']

        print(device)
        #reseting ip
        print("updating ip")
        #device = capabilities[deviceNAme]
        #chrome_cmd_off = 'docker exec -it 93948d769d64 adb shell svc data disable'
        #chrome_cmd_on = 'docker exec -it 93948d769d64 adb shell svc data enable'
        
        deviceId = {"ce031713e05ad8300d": "2cf3c833ac8c"}

        #chrome_cmd_off = 'docker exec -it ' + deviceId.get[device] +'adb shell svc data disable'
        #chrome_cmd_on = 'docker exec -it ' + deviceId.get[device] +'adb shell svc data enable'
        #os.popen(chrome_cmd_off)
        time.sleep(3)
        #os.popen(chrome_cmd_on)

        print("done")

        driver.quit
        return driver

        adb shell pm clear com.android.chrome'



def test_main():
    try:
        driver = drivercall()
        time.sleep(4)

        # Auto generated application URL parameter
        ApplicationURL = "https://bestbuy.com/?intl=nosplash"

        # 1. Run getOrder
        

        # 2. Pause for '5000'ms
        time.sleep(5)

        # 3. Run product_mobile_web
        test_product_mobile_web.test_main(driver)

        # 4. Pause for '5000'ms
        time.sleep(5)

        # 5. Run shipping_mobile_web
        test_shipping_mobile_web.test_main(driver)

        # 6. Pause for '5000'ms
        time.sleep(5)

        # 7. Run getGiftCards
        test_getgiftcards.test_main(driver)

        # 8. Pause for '5000'ms
        time.sleep(5)

        # 9. Run ApplyGiftCards
        test_applygiftcards.test_main(driver)

        # 10. Pause for '5000'ms
        time.sleep(5)

        # 11. Run sendOrderCornerCloud
        test_sendordercornercloud.test_main(driver)

        # 12. Pause for '5000'ms
        time.sleep(5)

        # 13. Run reportStepFinish

        driver.quit()     

        
    except Exception as e:
        print(str(e))
        def restart (){
            

        }
        driver.quit()   

