from selenium.webdriver.common.by import By
import time


"""
This pytest test was automatically generated by TestProject
    Project: AutomationOrderBestBuy
    Package: TestProject.Generated.Tests.AutomationOrderBestBuy
    Test: sendOrderCornerCloud
    Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
    Generated on 07/29/2021, 20:22:27
"""



def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://bestbuy.com/?intl=nosplash"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Scroll window by ('0','834')
    driver.execute_script("window.scrollBy(0,834)")

    # 3. Click 'Place Your Order1'
    place_your_order1 = driver.find_element(By.XPATH,
                                            "//button[. = 'Place Your Order']")
    place_your_order1.click()

    # 4. Scroll window by ('0','-90')
    driver.execute_script("window.scrollBy(0,-90)")

    # 5. Scroll window by ('0','-425')
    driver.execute_script("window.scrollBy(0,-425)")

    # 6. Scroll window by ('0','-35')
    driver.execute_script("window.scrollBy(0,-35)")

    # 7. Scroll window by ('0','-91')
    driver.execute_script("window.scrollBy(0,-91)")

    # 8. Scroll window by ('0','-4')
    driver.execute_script("window.scrollBy(0,-4)")

    # 9. Scroll window by ('0','-254')
    driver.execute_script("window.scrollBy(0,-254)")
