import time


"""
This pytest test was automatically generated by TestProject
    Project: AutomationOrderBestBuy
    Package: TestProject.Generated.Tests.AutomationOrderBestBuy
    Test: reportStepFinish
    Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
    Generated on 07/29/2021, 20:22:27
"""



def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://bestbuy.com/?intl=nosplash"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')
