from selenium.webdriver.common.by import By
import time
import time
from subtests import test_productattributes
from subtests import test_updatelocation
import project_parameters


"""
This pytest test was automatically generated by TestProject
    Project: AutomationOrderBestBuy
    Package: TestProject.Generated.Tests.AutomationOrderBestBuy
    Test: product_mobile_web
    Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
    Generated on 07/29/2021, 20:22:27
"""



def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://bestbuy.com/?intl=nosplash"

    # 1. Navigate to '{project_parameters.urlProduct_1}'
    driver.get(f'{project_parameters.urlProduct_1}')

    # 2. Pause for '3000'ms
    time.sleep(5)

    # 3. Run ProductAttributes
    test_productattributes.test_main(driver)

    # 4. Pause for '3000'ms
    time.sleep(5)

    # 5. Scroll window by ('0','805')
    driver.execute_script("window.scrollBy(0,805)")

    # 6. Click 'Add to Cart8'
    add_to_cart8 = driver.find_element(By.XPATH,
                                       "//button[. = 'Add to Cart']")
    add_to_cart8.click()

    # 7. Click 'Go to Cart7'
    go_to_cart7 = driver.find_element(By.XPATH,
                                      "//a[. = 'Go to Cart']")
    go_to_cart7.click()

    # 8. Run updateLocation
    test_updatelocation.test_main(driver)

    # 9. Click 'Included free (1 item)'
    included_free_1_item_ = driver.find_element(By.XPATH,
                                                "//div[. = 'Included free (1 item) ']")
    included_free_1_item_.click()

    # 10. Click 'Remove9'
    remove9 = driver.find_element(By.XPATH,
                                  "//div[4]//a[. = 'Remove']")
    remove9.click()

    # 11. Scroll window by ('0','-425')
    driver.execute_script("window.scrollBy(0,-425)")

    # 12. Click 'Checkout3'
    checkout3 = driver.find_element(By.XPATH,
                                    "//div[1]/div/div[2]/div/div[1]//button[. = 'Checkout']")
    checkout3.click()

    # 13. Scroll window by ('0','312')
    driver.execute_script("window.scrollBy(0,312)")

    # 14. Click 'Continue as Guest1'
    continue_as_guest1 = driver.find_element(By.XPATH,
                                             "//button[. = 'Continue as Guest']")
    continue_as_guest1.click()
